### ISSUE TITLE
Segmentfault encountered during rados/basic testing

### ISSUE THREAD

**Issue by xiexingguo** [ceph/dmclock#19] opened 2016-08-31 07:16 UTC
**Branch:**
https://github.com/ceph/ceph/tree/wip_dmc2_limits

**Testing job:**
 ```
description: rados:basic/{rados.yaml clusters/{fixed-2.yaml openstack.yaml} fs/btrfs.yaml
    mon_kv_backend/leveldb.yaml msgr/random.yaml msgr-failures/few.yaml tasks/repair_test.yaml}
```
**Symptom:**
There are a lot of crashes, see below:
```
2016-08-31T14:19:49.977 INFO:tasks.ceph.osd.0.plana120.stderr:*** Caught signal (Segmentation fault) **
2016-08-31T14:19:49.978 INFO:tasks.ceph.osd.0.plana120.stderr: in thread 7fb12d04c700 thread_name:ceph-osd
2016-08-31T14:19:49.979 INFO:tasks.ceph.osd.0.plana120.stderr: ceph version v11.0.0-1779-g94ce34c (94ce34ccc4f3ee62a95e902e6c5658e6eb04c671)
2016-08-31T14:19:49.981 INFO:tasks.ceph.osd.0.plana120.stderr: 1: (()+0x8865e2) [0x5622ea1ea5e2]
2016-08-31T14:19:49.982 INFO:tasks.ceph.osd.0.plana120.stderr: 2: (()+0x10340) [0x7fb1339b5340]
2016-08-31T14:19:49.983 INFO:tasks.ceph.osd.0.plana120.stderr: 3: (std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x1e) [0x5622e9d06e7e]
2016-08-31T14:19:49.984 INFO:tasks.ceph.osd.0.plana120.stderr: 4: (crimson::dmclock::PriorityQueueBase<ceph::mClockOpClassQueue::osd_op_type_t, std::pair<boost::intrusive_ptr<PG>, PGQueueable>, 2u>::do_clean()+0x729) [0x5622e9f6dfb9]
2016-08-31T14:19:49.986 INFO:tasks.ceph.osd.0.plana120.stderr: 5: (crimson::RunEvery::run()+0xd2) [0x5622ea1ebd8a]
2016-08-31T14:19:49.987 INFO:tasks.ceph.osd.0.plana120.stderr: 6: (()+0xb1a60) [0x7fb132bb4a60]
2016-08-31T14:19:49.988 INFO:tasks.ceph.osd.0.plana120.stderr: 7: (()+0x8182) [0x7fb1339ad182]
2016-08-31T14:19:49.989 INFO:tasks.ceph.osd.0.plana120.stderr: 8: (clone()+0x6d) [0x7fb13231c47d]
2016-08-31T14:19:49.990 INFO:tasks.ceph.osd.0.plana120.stderr:2016-08-31 14:19:49.973384 7fb12d04c700 -1 *** Caught signal (Segmentation fault) **
2016-08-31T14:19:49.991 INFO:tasks.ceph.osd.0.plana120.stderr: in thread 7fb12d04c700 thread_name:ceph-osd
2016-08-31T14:19:49.992 INFO:tasks.ceph.osd.0.plana120.stderr:
2016-08-31T14:19:49.993 INFO:tasks.ceph.osd.0.plana120.stderr: ceph version v11.0.0-1779-g94ce34c (94ce34ccc4f3ee62a95e902e6c5658e6eb04c671)
2016-08-31T14:19:49.994 INFO:tasks.ceph.osd.0.plana120.stderr: 1: (()+0x8865e2) [0x5622ea1ea5e2]
2016-08-31T14:19:49.995 INFO:tasks.ceph.osd.0.plana120.stderr: 2: (()+0x10340) [0x7fb1339b5340]
2016-08-31T14:19:49.998 INFO:tasks.ceph.osd.0.plana120.stderr: 3: (std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x1e) [0x5622e9d06e7e]
2016-08-31T14:19:49.999 INFO:tasks.ceph.osd.0.plana120.stderr: 4: (crimson::dmclock::PriorityQueueBase<ceph::mClockOpClassQueue::osd_op_type_t, std::pair<boost::intrusive_ptr<PG>, PGQueueable>, 2u>::do_clean()+0x729) [0x5622e9f6dfb9]
2016-08-31T14:19:50.000 INFO:tasks.ceph.osd.0.plana120.stderr: 5: (crimson::RunEvery::run()+0xd2) [0x5622ea1ebd8a]
2016-08-31T14:19:50.002 INFO:tasks.ceph.osd.0.plana120.stderr: 6: (()+0xb1a60) [0x7fb132bb4a60]
2016-08-31T14:19:50.003 INFO:tasks.ceph.osd.0.plana120.stderr: 7: (()+0x8182) [0x7fb1339ad182]
2016-08-31T14:19:50.004 INFO:tasks.ceph.osd.0.plana120.stderr: 8: (clone()+0x6d) [0x7fb13231c47d]
2016-08-31T14:19:50.004 INFO:tasks.ceph.osd.0.plana120.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-08-31T14:19:50.006 INFO:tasks.ceph.osd.0.plana120.stderr:
2016-08-31T14:19:50.040 INFO:tasks.ceph.osd.0.plana120.stderr:     0> 2016-08-31 14:19:49.973384 7fb12d04c700 -1 *** Caught signal (Segmentation fault) **
2016-08-31T14:19:50.042 INFO:tasks.ceph.osd.0.plana120.stderr: in thread 7fb12d04c700 thread_name:ceph-osd
2016-08-31T14:19:50.043 INFO:tasks.ceph.osd.0.plana120.stderr:
2016-08-31T14:19:50.044 INFO:tasks.ceph.osd.0.plana120.stderr: ceph version v11.0.0-1779-g94ce34c (94ce34ccc4f3ee62a95e902e6c5658e6eb04c671)
2016-08-31T14:19:50.045 INFO:tasks.ceph.osd.0.plana120.stderr: 1: (()+0x8865e2) [0x5622ea1ea5e2]
2016-08-31T14:19:50.046 INFO:tasks.ceph.osd.0.plana120.stderr: 2: (()+0x10340) [0x7fb1339b5340]
2016-08-31T14:19:50.047 INFO:tasks.ceph.osd.0.plana120.stderr: 3: (std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x1e) [0x5622e9d06e7e]
2016-08-31T14:19:50.048 INFO:tasks.ceph.osd.0.plana120.stderr: 4: (crimson::dmclock::PriorityQueueBase<ceph::mClockOpClassQueue::osd_op_type_t, std::pair<boost::intrusive_ptr<PG>, PGQueueable>, 2u>::do_clean()+0x729) [0x5622e9f6dfb9]
2016-08-31T14:19:50.050 INFO:tasks.ceph.osd.0.plana120.stderr: 5: (crimson::RunEvery::run()+0xd2) [0x5622ea1ebd8a]
2016-08-31T14:19:50.051 INFO:tasks.ceph.osd.0.plana120.stderr: 6: (()+0xb1a60) [0x7fb132bb4a60]
2016-08-31T14:19:50.052 INFO:tasks.ceph.osd.0.plana120.stderr: 7: (()+0x8182) [0x7fb1339ad182]
2016-08-31T14:19:50.053 INFO:tasks.ceph.osd.0.plana120.stderr: 8: (clone()+0x6d) [0x7fb13231c47d]
2016-08-31T14:19:50.054 INFO:tasks.ceph.osd.0.plana120.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-08-31T14:19:50.055 INFO:tasks.ceph.osd.0.plana120.stderr:
2016-08-31T14:19:50.249 INFO:tasks.ceph.osd.0.plana120.stderr:daemon-helper: command crashed with signal 11

**Comment by xiexingguo** [comment] 2016-08-31 07:16
@ivancich Eric, can you look?

**Comment by ivancich** [comment] 2016-08-31 14:36
The branch wip_dmc2_limits is a "work in progress" (that's what "wip" stands for). My intention for this branch is to work on dmClock strictly enforcing the limits in a ceph context. The work is not complete, however. I suspect the error is caused by a failed assertion, which is to be expected with the current state of the branch.

**Comment by ivancich** [comment] 2016-08-31 18:46
My apologies. I hadn't pushed my changes to the wip_dmc2_limits branch yet. So that branch was essentially the same as wip_dmclock2, and I wasn't aware of any bugs there. I will take a look.

**Comment by ivancich** [comment] 2016-09-06 19:36
I believe this has been addressed. I ran a test branch with the fix on teuthology using your same test using both dmclock2 op queues:

mclock_opclass: http://pulpito.ceph.com/ivancich-2016-09-03_16:32:34-dmclock:rados:basic-wip_dmc2_segfault1---basic-mira/

mclock_client: http://pulpito.ceph.com/ivancich-2016-09-03_16:54:35-dmclock:rados:basic-wip_dmc2_segfault1---basic-mira/

I merged it into wip_dmclock2 and am running the same tests on teuthology one more time.

**Comment by xiexingguo** [comment] 2016-09-07 03:33
@ivancich Thanks, Eric.

I think https://github.com/ceph/dmclock/commit/2baf442f9207326b1a60bd91742a2f82aaef293e is the right cure.

Feel free to close this.

**Closed** 2016-09-07 17:13 UTC
